version: '3.8'

services:
  media-controller:
    build: .
    container_name: media-controller
    ports:
      - "3001:3001"
    volumes:
      # Mount source code for development
      - ./src:/usr/src/app/src
      - ./views:/usr/src/app/views
      - ./dist:/usr/src/app/dist
      # Mount input device access (if available)
      - /dev/input:/dev/input:ro
      - /dev/uinput:/dev/uinput
    environment:
      - DISPLAY=host.docker.internal:0
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_RAWIO
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    restart: unless-stopped
